### ISSUE TITLE
Qusetion: Which mobile device is used? How can I run it on that phone?

### ISSUE THREAD

**Issue by nerososft** [oneOS-Project/oneOS#25]
Google Pixel?

**Comment by nimelehin** [comment]
Hey! Currently on a paper we do have an arm-v7 support, but I have't tested it on a real device yet, and I think it's require some more adaptations for a specific SoC to run on it. Current target is QEMU :)

**Comment by nerososft** [comment]
Got it, I'm looking forward to seeing it running on the device.
