### ISSUE TITLE
Build on macOS

### ISSUE THREAD

**Issue by jkvlogger** [oneOS-Project/oneOS#35]
hi oneOS-Project team so can you give build instructions to build oneOS on Mac??

**Comment by nimelehin** [comment]
Hey! There is a [build instruction](https://github.com/oneOS-Project/oneOS/blob/master/docs/build.md). Have you faced any problems following this?

**Comment by jkvlogger** [comment]
Installing packages
sudo: apt-get: command not found

**Comment by jkvlogger** [comment]
facing this error

**Comment by jkvlogger** [comment]
BUILD_TARGET     = i686-elf
BUILD_DIR        = /Users/username/build-i686-elf
BUILD_BINUTILS   = true
BUILD_GCC        = true
BUILD_GDB        = true
ZIP              = true
WIN              =
LINUX            =
ENV              =
x64              =
BINUTILS_VERSION = 2.35
GCC_VERSION      = 11.1.0
GDB_VERSION      = 9.2
PATH             = /opt/mxe/usr/bin:/Users/username/build-i686-elf/linux/output/bin:/Users/username/build-i686-elf/windows/output/bin:/Users/username/.rvm/gems/ruby-2.7.2/bin:/Users/username/.rvm/gems/ruby-2.7.2@global/bin:/Users/username/.rvm/rubies/ruby-2.7.2/bin:/usr/local/opt/make/libexec/gnubin:/usr/local/opt/binutils/bin:/usr/local/opt/e2fsprogs/sbin:/usr/local/opt/e2fsprogs/bin:/usr/local/opt/e2fsprogs/sbin:/usr/local/opt/e2fsprogs/bin:/usr/local/opt/llvm/bin:/usr/local/opt/llvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/Volumes/Macintosh-Data/flutter/bin:/Users/username/.pub-cache/bin:/Users/username/go/bin:/Users/username/go/pkg/mod:/Users/username/go/src:/usr/local/bin:/Users/username/.rvm/bin
Installing packages
sudo: apt-get: command not found

**Comment by jkvlogger** [comment]
can you help me to fix it?

**Comment by jkvlogger** [comment]
I have installed all the dependencies you mentioned for Mac

**Comment by jkvlogger** [comment]
I just commented the installPackages function cause it works only on linux
after commenting it I face this issue

**Comment by jkvlogger** [comment]
Installing MXE
    Cloning MXE and compiling mingw32.static GCC
fatal: destination path 'mxe' already exists and is not an empty directory.

**Comment by nimelehin** [comment]
Seems you try to run a script to build a tool chain, while this script is for Linux. For macos use brew formulae (https://formulae.brew.sh/formula/i686-elf-gcc)

**Comment by jkvlogger** [comment]
Warning: i686-elf-gcc 11.2.0 is already installed and up-to-date.
To reinstall 11.2.0, run:
  brew reinstall i686-elf-gcc

**Comment by jkvlogger** [comment]
I already installed it

**Comment by nimelehin** [comment]
if you have an i686-elf-gcc installed, go to [building of the OS](https://github.com/oneOS-Project/oneOS/blob/master/docs/build.md#building-os)

**Comment by jkvlogger** [comment]
> Installing MXE
> Cloning MXE and compiling mingw32.static GCC
> fatal: destination path 'mxe' already exists and is not an empty directory.


after install  i686-elf-gcc I face this issue

**Comment by jkvlogger** [comment]
![Untitled](https://user-images.githubusercontent.com/82597333/128599046-69c16615-9e9a-489e-adac-0768b1d2f258.jpg)

**Comment by jkvlogger** [comment]
![Untitled](https://user-images.githubusercontent.com/82597333/128599076-9722405c-0a5f-40d1-a28d-f244fe92c617.jpg)

**Comment by jkvlogger** [comment]
screenshot of the error

**Comment by nimelehin** [comment]
What command do you try to run? You have to run `./gn_gen.sh`.

**Comment by jkvlogger** [comment]
oops ok

**Comment by jkvlogger** [comment]
how to run??

**Comment by jkvlogger** [comment]
./gn_gen.sh: line 22: gn: command not found
[ERROR] Can't do gn gen

**Comment by jkvlogger** [comment]
> ./gn_gen.sh: line 22: gn: command not found
> [ERROR] Can't do gn gen

I just run the command that you gave I face this error

**Comment by nimelehin** [comment]
Have you installed gn? [Downlod it from here](https://github.com/oneOS-Project/oneOS/blob/master/docs/getting_gn.md). and after that move `gn` binary to `/usr/local/bin` using command in a terminal from a downloaded folder with gn `mv gn /usr/local/bin`.

**Comment by jkvlogger** [comment]
let me download it

**Comment by jkvlogger** [comment]
hi @nimelehin I've installed and it runs after I type ```./gn_gen.sh```

**Comment by jkvlogger** [comment]
now running ./build.sh in out/

**Comment by nimelehin** [comment]
you can run `./all.sh` in `out/` to build and run with one command.

**Comment by jkvlogger** [comment]
thanks for your help brother

**Comment by jkvlogger** [comment]
😄
